baseURL = 'https://blog.mugee.uk/'
languageCode = 'zh-cn'
title = "mugee's personal space"
theme = 'hugo-theme-terminal'

[params]
  description = "一个在 Arch Linux 上写代码的极客"
  background_color_class = "bg-black" # 经典的极客黑顶栏
