baseURL = 'https://blog.mugee.uk/'
languageCode = 'zh-cn'
title = "mugee"
theme = 'hugo-coder'
hasCJKLanguage = true
summaryLength = 70

[pagination]
pagerSize = 20

[markup.highlight]
style = 'github-dark'

[params]
  author = "Mugee"
  info = "一个在 Arch Linux 上写代码的极客"
  description = "Mugee's personal website"
  keywords = "blog, developer, personal"
  since = 2026

  colorScheme = "auto"
  hidecolorschemetoggle = false

  avatarurl = "images/avatar.jpg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "posts"
  icon = "fa-regular fa-newspaper fa-2x"
  weight = 1
  url = "http://blog.mugee.uk/posts"

[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 1
  url = "https://www.instagram.com/enochliu0318"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/enochliu0318"

[[menu.main]]
  name = "文章"
  weight = 1
  url = "/posts/"

[[menu.main]]
  name = "标签"
  weight = 2
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 3
  url = "/categories/"

[[menu.main]]
  name = "关于"
  weight = 4
  url = "/about/"


